# Generated by Django 4.2.4 on 2023-11-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkweb', '0002_role_subject_user_phone_number_user_preis_pro_45_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkweb.role'),
        ),
    ]
