# Generated by Django 4.2.4 on 2023-12-29 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkweb', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tutoring',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Duration must be greater than 0.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
