# Generated by Django 4.2.4 on 2023-12-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0004_alter_role_title_alter_tutoring_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="title",
            field=models.CharField(
                choices=[("Student", "Student"), ("Teacher", "Teacher"), ("Developer", "Developer")], max_length=10
            ),
        ),
    ]
