# Generated by Django 4.2.4 on 2023-12-31 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0004_alter_role_title_alter_tutoring_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
