# Generated by Django 4.2.4 on 2024-01-01 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0005_remove_user_role_delete_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoring",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
