# Generated by Django 4.2.4 on 2023-12-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0005_alter_role_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="checkweb.role"),
        ),
    ]
