# Generated by Django 4.2.4 on 2023-12-30 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0006_alter_user_email_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
