# Generated by Django 4.2.4 on 2024-01-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0006_alter_tutoring_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
