# Generated by Django 4.2.4 on 2024-01-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0007_alter_subject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoring",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
