# Generated by Django 4.2.4 on 2023-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0008_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
