# Generated by Django 4.2.4 on 2024-01-02 00:20

import checkweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0008_tutoring_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoring",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="pdfs/", validators=[checkweb.models.validate_pdf]
            ),
        ),
    ]
