# Generated by Django 4.2.4 on 2023-12-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
