# Generated by Django 4.2.4 on 2024-01-02 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0009_alter_tutoring_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoring",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_tutorings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
