# Generated by Django 4.2.4 on 2024-01-02 15:56

import checkweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0010_alter_tutoring_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdfs/",
                        validators=[checkweb.models.validate_pdf],
                    ),
                ),
            ],
        ),
    ]
