# Generated by Django 4.2.4 on 2024-01-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkweb", "0011_fileupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileUpload",
        ),
        migrations.AddField(
            model_name="tutoring",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
