name: Django CI

on: [push, pull_request, workflow_dispatch]

jobs:

  LOCAL:
    runs-on: ubuntu-latest
    environment: LOCAL
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      PERSONAL_TEACHER_CODE: ${{ secrets.PERSONAL_TEACHER_CODE }}
      LOCAL: ${{ secrets.LOCAL }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Run docker-compose
      uses: docker://docker/compose:latest
      with:
        args: up --build -d
    - name: Migrate and Run Tests
      run: |
        docker ps
        docker exec -it workspace_django_1 /bin/bash
        # python manage.py migrate --verbosity 3
        # python manage.py test