name: Django CI

on: [push, pull_request, workflow_dispatch]

jobs:

  LOCAL:
    runs-on: ubuntu-latest
    environment: LOCAL
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      PERSONAL_TEACHER_CODE: ${{ secrets.PERSONAL_TEACHER_CODE }}
      LOCAL: ${{ secrets.LOCAL }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Set up Docker-Compose
      run: |
        DOCKER_COMPOSE_VERSION=2.20.2
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    - name: Run docker-compose
      run: docker-compose up --build -d
    # - name: Migrate and Run Tests
    #   run: |
    #     python manage.py migrate --verbosity 3
    #     python manage.py test