name: Docker Image CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    # --build-arg: unterbindet in github workflow copy .env in Dockerfile
      run: docker build . --file Dockerfile --tag django-docker:0.0.1 --build-arg ENVIRONMENT=github